"""CubeEngine renderer-neutral Scene IR v2."""

from .scene_ir import (
    SCENE_COMPILER_CAPABILITIES,
    SCENE_COMPILER_CAPABILITY_ID,
    SCENE_COMPILER_CAPABILITY_PATH,
    SCENE_IR_SCHEMA_PATH,
    SCENE_IR_PATCH_SCHEMA_PATH,
    SCENE_IR_VERSION,
    SceneIRDiagnostic,
    canonical_scene_ir_hash,
    identity_matrix,
    identity_transform,
    is_scene_ir_compile_ready,
    load_scene_ir,
    new_scene_ir,
    seal_scene_ir,
    validate_scene_ir,
)
from .compiler import (
    CompiledBinding,
    CompiledComponent,
    CompiledNode,
    CompiledPrefab,
    CompiledScene,
    SceneCommand,
    SceneCompileError,
    SceneDelta,
    SceneProjectionError,
    SceneProjectionSession,
    compile_scene_ir,
)
from .conformance import SceneIRConformanceReport, assess_scene_ir_conformance
from .patching import SceneIRPatchError, apply_scene_ir_patch

__all__ = [
    "SCENE_COMPILER_CAPABILITIES",
    "SCENE_COMPILER_CAPABILITY_ID",
    "SCENE_COMPILER_CAPABILITY_PATH",
    "SCENE_IR_SCHEMA_PATH",
    "SCENE_IR_PATCH_SCHEMA_PATH",
    "SCENE_IR_VERSION",
    "SceneIRDiagnostic",
    "canonical_scene_ir_hash",
    "identity_matrix",
    "identity_transform",
    "is_scene_ir_compile_ready",
    "load_scene_ir",
    "new_scene_ir",
    "seal_scene_ir",
    "validate_scene_ir",
    "CompiledBinding",
    "CompiledComponent",
    "CompiledNode",
    "CompiledPrefab",
    "CompiledScene",
    "SceneCommand",
    "SceneCompileError",
    "SceneDelta",
    "SceneProjectionError",
    "SceneProjectionSession",
    "compile_scene_ir",
    "SceneIRConformanceReport",
    "assess_scene_ir_conformance",
    "SceneIRPatchError",
    "apply_scene_ir_patch",
]
