"""CubeEngine Input IR v2 and deterministic semantic input compiler."""

from .input_ir import (
    INPUT_COMPILER_CAPABILITIES,
    INPUT_COMPILER_CAPABILITY_ID,
    INPUT_COMPILER_CAPABILITY_PATH,
    INPUT_IR_PATCH_SCHEMA_PATH,
    INPUT_IR_SCHEMA_PATH,
    INPUT_IR_VERSION,
    InputIRDiagnostic,
    canonical_input_ir_hash,
    default_processing,
    is_input_ir_compile_ready,
    load_input_ir,
    new_input_ir,
    seal_input_ir,
    validate_input_ir,
    validate_trigger,
)
from .compiler import (
    CompiledBinding,
    CompiledContext,
    CompiledInputMap,
    CompiledIntent,
    InputCompileError,
    InputConflict,
    InputDispatch,
    InputDispatchError,
    InputRouter,
    InputRouterSnapshot,
    PhysicalInputEvent,
    ResolvedIntent,
    RuleActionRequest,
    compile_input_ir,
)
from .conformance import InputIRConformanceReport, assess_input_ir_conformance
from .patching import InputIRPatchError, apply_input_ir_patch

__all__ = [
    "INPUT_COMPILER_CAPABILITIES",
    "INPUT_COMPILER_CAPABILITY_ID",
    "INPUT_COMPILER_CAPABILITY_PATH",
    "INPUT_IR_PATCH_SCHEMA_PATH",
    "INPUT_IR_SCHEMA_PATH",
    "INPUT_IR_VERSION",
    "InputIRDiagnostic",
    "canonical_input_ir_hash",
    "default_processing",
    "is_input_ir_compile_ready",
    "load_input_ir",
    "new_input_ir",
    "seal_input_ir",
    "validate_input_ir",
    "validate_trigger",
    "CompiledBinding",
    "CompiledContext",
    "CompiledInputMap",
    "CompiledIntent",
    "InputCompileError",
    "InputConflict",
    "InputDispatch",
    "InputDispatchError",
    "InputRouter",
    "InputRouterSnapshot",
    "PhysicalInputEvent",
    "ResolvedIntent",
    "RuleActionRequest",
    "compile_input_ir",
    "InputIRConformanceReport",
    "assess_input_ir_conformance",
    "InputIRPatchError",
    "apply_input_ir_patch",
]
