"""CubeEngine IR v2 draft contracts."""

from .rule_ir import (
    RULE_IR_VERSION,
    RuleIRDiagnostic,
    canonical_rule_ir_hash,
    is_rule_ir_compile_ready,
    load_rule_ir,
    new_rule_ir,
    seal_rule_ir,
    validate_rule_ir,
)
from .migration import upgrade_rule_schema_v1
from .expression import EvaluationContext, ExpressionError, ExpressionEvaluator, FunctionSpec
from .runtime import (
    ActionInstance,
    IllegalActionError,
    InvariantDiagnostic,
    InvariantViolation,
    OutcomeResult,
    RuleRuntime,
    RuleRuntimeError,
    RuleState,
    TransitionReport,
    compile_rule_ir,
    replay_rule_ir,
)
from .event_time import (
    JointTransitionReport,
    ReplayEntry,
    RuntimeEventReport,
    SchedulerTraceEntry,
    TimeAdvanceReport,
)
from .topology import (
    TopologyQueryError,
    bracketed_run,
    bracketed_sites,
    connected,
    directions,
    has_bracketed_site,
    neighbors,
    ray,
    region,
    shortest_path,
)
from .types import BUILTIN_TYPES, RuleTypeError, RuleTypeRegistry
from .authoring import (
    ResolvedRuleConfiguration,
    RuleConfigurationError,
    resolve_rule_configuration,
)
from .patching import RuleIRPatchError, apply_rule_ir_patch
from .capabilities import (
    RULE_RUNTIME_CAPABILITIES,
    RULE_RUNTIME_CAPABILITY_ID,
    RULE_RUNTIME_CAPABILITY_PATH,
    runtime_capability_diagnostics,
)
from .conformance import RuleIRConformanceReport, assess_rule_ir_conformance
from .random_service import (
    RANDOM_SERVICE_CAPABILITY_ID,
    PCG32_ALGORITHM,
    RECORDED_ALGORITHM,
    SUPPORTED_ALGORITHMS,
    SUPPORTED_DISTRIBUTIONS,
    SUPPORTED_SEED_POLICIES,
    ChanceResult,
    DeterministicRandomService,
    PCG32,
    RandomServiceError,
)

__all__ = [
    "RULE_IR_VERSION",
    "RuleIRDiagnostic",
    "canonical_rule_ir_hash",
    "is_rule_ir_compile_ready",
    "load_rule_ir",
    "new_rule_ir",
    "seal_rule_ir",
    "validate_rule_ir",
    "upgrade_rule_schema_v1",
    "EvaluationContext",
    "ExpressionError",
    "ExpressionEvaluator",
    "FunctionSpec",
    "ActionInstance",
    "IllegalActionError",
    "InvariantDiagnostic",
    "InvariantViolation",
    "OutcomeResult",
    "RuleRuntime",
    "RuleRuntimeError",
    "RuleState",
    "TransitionReport",
    "compile_rule_ir",
    "replay_rule_ir",
    "JointTransitionReport",
    "ReplayEntry",
    "RuntimeEventReport",
    "SchedulerTraceEntry",
    "TimeAdvanceReport",
    "TopologyQueryError",
    "bracketed_run",
    "bracketed_sites",
    "connected",
    "directions",
    "has_bracketed_site",
    "neighbors",
    "ray",
    "region",
    "shortest_path",
    "BUILTIN_TYPES",
    "RuleTypeError",
    "RuleTypeRegistry",
    "ResolvedRuleConfiguration",
    "RuleConfigurationError",
    "resolve_rule_configuration",
    "RuleIRPatchError",
    "apply_rule_ir_patch",
    "RULE_RUNTIME_CAPABILITY_ID",
    "RULE_RUNTIME_CAPABILITIES",
    "RULE_RUNTIME_CAPABILITY_PATH",
    "runtime_capability_diagnostics",
    "RuleIRConformanceReport",
    "assess_rule_ir_conformance",
    "RANDOM_SERVICE_CAPABILITY_ID",
    "PCG32_ALGORITHM",
    "RECORDED_ALGORITHM",
    "SUPPORTED_ALGORITHMS",
    "SUPPORTED_DISTRIBUTIONS",
    "SUPPORTED_SEED_POLICIES",
    "ChanceResult",
    "DeterministicRandomService",
    "PCG32",
    "RandomServiceError",
]
